spring.application.name=setlist-builder

#Server port
server.port=8080

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/setlist_builder
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# JPA - validate means Hibernate checks entities match the schema but does NOT change it
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway - automatically runs pending migrations on startup
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
app.jwt.secret=${JWT_SECRET:change-this-secret-in-production}
app.jwt.expiration-ms=86400000

# Spotify
app.spotify.client-id=${SPOTIFY_CLIENT_ID}
app.spotify.client-secret=${SPOTIFY_CLIENT_SECRET}
app.spotify.artist-name=bombazine
app.spotify.base-url=https://api.spotify.com/v1
app.spotify.auth-url=https://accounts.spotify.com/api/token
app.spotify.artist-id=5u1k62yUtsOIqf1U4wIQ8N?si=cd35022469ca44c0