spring.application.name=setlist-builder

#Server port
server.port=8080

#Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA - validate means Hibernate checks entities match the schema but does NOT change it
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Flyway - automatically runs pending migrations on startup
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

# Spotify - Due to the changes in the Spotify API which removed the popularity attribute and is limiting api calls for personal use, I've pivoted to the Last.fm API. The information is kept in the project merely for demonstration purposes
#app.spotify.client-id=${SPOTIFY_CLIENT_ID}
#app.spotify.client-secret=${SPOTIFY_CLIENT_SECRET}
#app.spotify.artist-name=bombazine
#app.spotify.base-url=https://api.spotify.com/v1
#app.spotify.auth-url=https://accounts.spotify.com/api/token
#app.spotify.artist-id=5u1k62yUtsOIqf1U4wIQ8N
#app.spotify.market=PT

#Last.fm
app.lastfm.api-key=${LAST_FM_API_KEY}
app.lastfm.artist-name=bombazine